# Build IBM cloud controller manager binary
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.20 AS ccm-builder
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o ibm-cloud-controller-manager .

# Assemble the final image
FROM registry.ci.openshift.org/ocp/4.20:base-rhel9
LABEL description="IBM Cloud Controller Manager"
COPY --from=ccm-builder /build/ibm-cloud-controller-manager /bin/ibm-cloud-controller-manager
ENTRYPOINT [ "/bin/ibm-cloud-controller-manager" ]
