# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # location of your .github/workflows directory
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "github-actions"
      - "release-1.34"
    ignore:
      - dependency-name: "golangci/golangci-lint-action" # Need to use older version
    target-branch: "release-1.34"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 8 * * *" # Run at 8:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.34:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.34:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.34"
  #   target-branch: "release-1.34"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 7 * * *" # Run at 7:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.33:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.33:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.33"
  #   target-branch: "release-1.33"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 6 * * *" # Run at 6:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.32:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.32:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.32"
  #   target-branch: "release-1.32"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 5 * * *" # Run at 5:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.31:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.31:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.31"
  #   target-branch: "release-1.31"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 4 * * *" # Run at 4:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.30:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.30:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.30"
  #   target-branch: "release-1.30"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 3 * * *" # Run at 3:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.29:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.29:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.29"
  #   target-branch: "release-1.29"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 2 * * *" # Run at 2:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.28:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.28:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.28"
  #   target-branch: "release-1.28"

  # - package-ecosystem: "gomod" # Specifies the Go modules package ecosystem
  #   directory: "/" # Location of your go.mod file
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 1 * * *" # Run at 1:00 UTC daily
  #   ignore:
  #     - dependency-name: "k8s.io/api"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/apimachinery"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/client-go"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/cloud-provider"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-base"
  #       update-types: ["version-update:semver-minor"]
  #     - dependency-name: "k8s.io/component-helpers"
  #       update-types: ["version-update:semver-minor"]
  #   open-pull-requests-limit: 99
  #   groups:
  #     kubernetes-1.27:
  #       patterns:
  #         - "k8s.io/*"
  #     ibm-sdk-1.27:
  #       patterns:
  #         - "github.com/IBM/*"
  #   labels:
  #     - "dependencies"
  #     - "go"
  #     - "release-1.27"
  #   target-branch: "release-1.27"
