# This workflow will run actionLint against github workflows

name: GitHub Actions Lint

on:
  push:
    paths:
      - '**.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
