# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".golangci.yml"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".golangci.yml"
      - ".github/workflows/go.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go and golangci-lint versions
        id: get-ver
        run: |
          echo "go_version=$(grep '^go ' go.mod | awk '{ print $2 }')" >> $GITHUB_OUTPUT
          echo "golangci_version=v$(grep '^GOLANGCI_LINT_VERSION ' Makefile | awk '{ print $3 }')" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.get-ver.outputs.go_version }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6 # v8 available, but only supports >= v2.1.0
        with:
          args: --disable-all --timeout 5m # disable linting, initialize cache
          version: ${{ steps.get-ver.outputs.golangci_version }}

      - name: Run go fmt (via golangci-lint)
        run: make fmt

      - name: Run lint (via golangci-lint)
        run: make lint

      - name: Rnn go vet
        run: make vet

      - name: Run go test
        run: make test

      - name: Run go build
        run: make ccm
