name: Golangci-lint Update

on:
  schedule:
    - cron: "0 12 * * *" # Run at 12:00 UTC daily
  workflow_dispatch: # Allow manual triggering

jobs:
  golangci-update:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [release-1.34]
    steps:
      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout branch ${{ matrix.branch }}
        uses: actions/checkout@v5
        with:
          ref: ${{ matrix.branch }}

      - name: Get current golangci-lint version for ${{ matrix.branch }}
        id: current
        run: |
          echo "version=v$(grep '^GOLANGCI_LINT_VERSION ' Makefile | awk '{ print $3 }')" >> "$GITHUB_OUTPUT"

      - name: Get latest golangci-lint release
        id: latest
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/golangci/golangci-lint/releases/latest | jq -r .tag_name)
          echo "version=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: No update needed for ${{ matrix.branch }}
        if: steps.current.outputs.version == steps.latest.outputs.version
        run: |
          echo "No update needed"

      - name: Update code and commit changes
        if: steps.current.outputs.version != steps.latest.outputs.version
        id: commit-change
        run: |
          sed -i -e "s/GOLANGCI_LINT_VERSION := ${CURRENT:1}/GOLANGCI_LINT_VERSION := ${LATEST:1}/g" Makefile
          commit_msg="Bump golangci-lint from ${{ steps.current.outputs.version }} to ${{ steps.latest.outputs.version }} in branch ${{ matrix.branch }}"
          echo "msg=$commit_msg" >> "$GITHUB_OUTPUT"
          git add Makefile
          git commit -m "$commit_msg"
        env:
          CURRENT: ${{ steps.current.outputs.version }}
          LATEST: ${{ steps.latest.outputs.version }}

      - name: Create pull request
        if: steps.current.outputs.version != steps.latest.outputs.version
        uses: peter-evans/create-pull-request@v7
        with:
          title: ${{ steps.commit-change.outputs.msg }}
          body: |
            If you do not see:

              ✅ Tests completed successfully

            Check the PR results [here](https://github.com/IBM-Cloud/cloud-provider-ibm/actions/workflows/dispatch-pr-create.yml)
          commit-message: ${{ steps.commit-change.outputs.msg }}
          branch: golangci-${{ steps.latest.outputs.version }}
          base: ${{ matrix.branch }}
          labels: |
            kube-update
            ${{ matrix.branch }}
          delete-branch: true

      - name: Trigger downstream workflow
        if: steps.current.outputs.version != steps.latest.outputs.version
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: pull-request-created
          client-payload: |
            {
              "pr_branch": "golangci-${{ steps.latest.outputs.version }}",
              "pr_title": "${{ steps.commit-change.outputs.msg }}"
            }
