# This workflow will run Super-linter against the repo

name: Lint

on:
  push:
    paths:
      - "**.md"
      - "**.sh"
      - "**.yml"
    branches:
      - release-1.34
      - release-1.33
  pull_request:
    paths:
      - "**.md"
      - "**.sh"
      - "**.yml"
    branches:
      - release-1.34
      - release-1.33
  workflow_dispatch: # Allow manual triggering

jobs:
  lint:
    name: Lint Github Actions
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # To report GitHub Actions status checks
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
